# we will be exploring fundamental function of tensorflow

More specifically we are goint to do the following
* introduction to tensors
* getting information from tensors
* Manupilating tensors
* Tensors & numpy
* using @tf.function (for speeding up the python function)
* using GPU and TPU
* exercise to try your self

## Introduction to tensors

### Lecture 16
creating tensor (Constant)





In [1]:
#import tensorflow

import tensorflow as tf

print (tf.__version__)

2.12.0


In [2]:
# creating a tensor

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#dimention of tensor
scalar.ndim

0

In [4]:
# creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# ndim of vector
vector.ndim

1

In [6]:
# creating a matrix
matrix = tf.constant([[10,10],
                      [10,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
from numpy import float16
# another matrix

another_matrix = tf.constant( [[7. , 8.],
                               [9. , 8.],
                               [7. ,8. ]] , dtype=float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[7., 8.],
       [9., 8.],
       [7., 8.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# creating tensor

tensor = tf.constant([[[1,2,3],
                       [1,2,3]],
                      [[5,4,2],
                      [7,8,9]
                      ]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[5, 4, 2],
        [7, 8, 9]]], dtype=int32)>

In [11]:
tensor.ndim

3


What we learned so Far

* scalar is 0 dimention
* vector is 1 dimention
* matrix is 2 dimention
* tensor is n- dimention

### Lecture 17
Creating Changeable tensor (Variable)

In [12]:
# creating tensors with  help of tf.Variable

changeable_tensor  = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7] )

changeable_tensor , unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# accessing the value by index
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


### Lecture 18
**creating Random tensors**
Random tensors are tenser with some arbitary size with random values


In [14]:
# creating a random tensor

random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(2,2))
random2 = tf.random.Generator.from_seed(42)
random2 =random2.normal(shape=(2,2))
random1 , random2 , random1==random2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

## Lecture 19
suffle the tensor

In [15]:
# tensor we want to shuffle
tensor_shuffle = tf.constant([[1,2,3],
                            [4,5,6],
                              [7,8,9],
                              [11,12,13]])

In [16]:
# shuffle
tf.random.shuffle(tensor_shuffle )

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [ 1,  2,  3],
       [11, 12, 13],
       [ 4,  5,  6]], dtype=int32)>

In [17]:
# seting an seed  = 42 which is a global
tf.random.set_seed=42

In [18]:
tf.random.shuffle(tensor_shuffle , seed=42)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 12, 13],
       [ 4,  5,  6]], dtype=int32)>

***conclusion -- set_seed  and seed ***
there are two seed one is global and one is local
inorder to get a specific result in a point of time u have to set both seed
if eather of seed is set to none the random value will come out

## Lecture 20
creating tensors with numpy and creating it to a tensor

In [19]:
# creating all ones in tensor
tf.ones(shape=[2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
# creating all zeros in tensor
tf.zeros(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
# creating an numpy array
import numpy as np

# Note when you create matrix or tensor use a capital letter   ex = X
# if you create a scalar or a vector use small letter          example  =y

numpy_a = np.array(np.arange(0,24) , dtype= np.int32)
numpy_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)

In [22]:
# creating tensor with numpy

tf.constant(numpy_a)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [23]:
# we create numpy to a tensor because tensor are good in calculation
tf.constant(numpy_a, shape=(4,3,2))

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]], dtype=int32)>

## Lecture 21
getting more information from the tensors
* shape
* rank
* axis or dimention
* size

In [24]:
# creating a tensor and using the above functions

tensor_  = tf.zeros( shape=[2,3,4,5] , dtype=tf.int32)
tensor_

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [25]:
print("data type - ",tensor_.dtype)
print("number of dimention  - ",tensor_.ndim)
print("shape - ",tensor_.shape)
print("number of 0 dimention - ",tensor_.shape[0])
print("number of last dimention - ",tensor_.shape[-1])
print("size - ",tf.size(tensor_).numpy())

data type -  <dtype: 'int32'>
number of dimention  -  4
shape -  (2, 3, 4, 5)
number of 0 dimention -  2
number of last dimention -  5
size -  120


## Lecture 22

using indexing on tensor

In [26]:

#getting first 2 element of each dimenion

tensor_indexing = tf.zeros(shape=[3,4,5,6])
tensor_indexing

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

In [27]:
# getting first two element of all dimetion
tensor_indexing[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get a first  element from each dimention exept the last dimention

In [29]:
tensor_indexing[:1,:1,:1 ,]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# geting a last element of a last dimention in a tensor
tensor_rank_2 = tf.constant([[10,7],
                             [3,4]])
tensor_rank_2[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
# creating an another dimention

tensor_rank_3 = tensor_rank_2[...,tf.newaxis]  #   ( ... ) === ( : , : , : ) tells all the dimention before the curr
tensor_rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
# alternative for tf.newaxis

tf.expand_dims(tensor_rank_2,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
tf.expand_dims(tensor_rank_2 , axis=0 )

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Lecture 23
**Manipulating tensor**
`+`
`-`
`/`
`*`

In [34]:
# creating a tensor

tensor = tf.constant([[10, 7],
                     [3 , 4]])


tensor*3 , tensor/3 , tensor-3 , tensor+3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 21],
        [ 9, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[3.33333333, 2.33333333],
        [1.        , 1.33333333]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[7, 4],
        [0, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 10],
        [ 6,  7]], dtype=int32)>)

###### NOTE - always remember to use tf.math.multiply ( kind of operation ) because they are fast for gpu computation where as the normal operator are expensive

In [35]:
tf.math.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

## Lecture 24
**Matrix Multiplication**

In [36]:
# matrix multiplication
A = tf.constant([[10, 7],
                 [7,10]])
B = tf.constant([[11,15],
                 [12,19]])

C = tf.matmul(A,B)
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[194, 283],
       [197, 295]], dtype=int32)>

In [37]:
# if we use an operator to do the multiplicaiton of tensor it will do it element vice

A*B==C
# not equal beacuse there is a element based multiplicaiton

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [38]:
# matrix multipalicaion with @ symbol

A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[194, 283],
       [197, 295]], dtype=int32)>

In [39]:
# matrix multiplicaiton of two different shape tensor

A = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
B = tf.constant([[4 ,5 ,6],
                 [7 ,8 ,9]])

tf.matmul(A,B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 24],
       [40, 47, 54],
       [62, 73, 84]], dtype=int32)>

## Lecture 25
**Matrix multiplicaiton rules**

1. inner dimention should match
2. resultin Matrix will be of outer dimention

In [40]:
A = tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])

B = tf.constant([[1,2,3],
                 [4,5,6]])

A.shape , B.shape

(TensorShape([3, 3]), TensorShape([2, 3]))

In [41]:
# inorder to multiply  the we can reshape a tensor
A @ (tf.reshape(B,shape=[3,2]))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

In [42]:
# inorder to multiply  the we can transpose a tensor
A @ (tf.transpose(B))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 14,  32],
       [ 32,  77],
       [ 50, 122]], dtype=int32)>

## Lecture 26
always use transpose rather than reshape


In [43]:
A = tf.constant(np.arange(1,13),shape=(3,4))
B = tf.constant(np.arange(13,25),shape=(3,4))
A , B

(<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])>,
 <tf.Tensor: shape=(3, 4), dtype=int64, numpy=
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>)

In [44]:
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])>

#Lecture 27
**Changing data type of the tensor**

using a float16  is faster than float32 (float32 is defalut precision)

using a int16  is faster than int32 (int32 is defalut precision)

In [45]:
# creatin two tensors one with int32 and second with  float32

a = tf.constant([1,2,3])
b = tf.constant([1.,2.,3.])

a , b

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>)

In [46]:
#changing the dtype of the tensor
tf.cast(a,dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

## Lecture 28

**aggregate function in tensor**

1. absolute
2. mean
2. min
3. max
4. sum
5. standard daviation
6. variance

In [47]:
# creating a tesor to apply all aggregate function

tensor_rank_1  = tf.constant(np.random.randint(low=0 ,high=25 ,size=50))
tensor_rank_1

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1,  8, 16, 17,  4, 20, 11, 10,  2, 19,  3,  9,  6, 11, 21,  2, 10,
       13,  7, 16,  8, 20,  4, 12, 12,  2,  6, 12,  4,  2, 24,  8, 14,  3,
       15, 20,  9,  4,  8, 21, 11,  0, 20, 19, 18,  3, 16, 22, 17,  7])>

In [48]:
# gives absolute value by element
tensor_test = tf.constant([4,-2,-8])

tf.abs(tensor_test)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 8], dtype=int32)>

In [49]:
print("maximum of tensor - ", tf.reduce_max(tensor_rank_1))
print("minimum of tensor - ", tf.reduce_min(tensor_rank_1))
print("mean of tensor - ", tf.reduce_mean(tensor_rank_1))
print("sum of tensor - ", tf.reduce_sum(tensor_rank_1))
tensor_rank_1 = tf.cast(tensor_rank_1, dtype= tf.float32)  # to get variance and standard daviation convert the tensor into flaot
print("variance of tensor - ",tf.math.reduce_variance(tensor_rank_1))
print("standard daviation of tensor - ",tf.math.reduce_std(tensor_rank_1))

maximum of tensor -  tf.Tensor(24, shape=(), dtype=int64)
minimum of tensor -  tf.Tensor(0, shape=(), dtype=int64)
mean of tensor -  tf.Tensor(10, shape=(), dtype=int64)
sum of tensor -  tf.Tensor(547, shape=(), dtype=int64)
variance of tensor -  tf.Tensor(44.616398, shape=(), dtype=float32)
standard daviation of tensor -  tf.Tensor(6.6795506, shape=(), dtype=float32)


## Lecture 30
finding postional maximum and minimum in a tensor

In [50]:
# using tensor_rank_1 tensor
tensor_rank_1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 1.,  8., 16., 17.,  4., 20., 11., 10.,  2., 19.,  3.,  9.,  6.,
       11., 21.,  2., 10., 13.,  7., 16.,  8., 20.,  4., 12., 12.,  2.,
        6., 12.,  4.,  2., 24.,  8., 14.,  3., 15., 20.,  9.,  4.,  8.,
       21., 11.,  0., 20., 19., 18.,  3., 16., 22., 17.,  7.],
      dtype=float32)>

In [51]:
# positional maximum
tf.math.argmax(tensor_rank_1)



<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [52]:
# positional minimum
tf.math.argmin(tensor_rank_1)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

## Lecture 31
 ***Squeezing tensor (removing all single dimention )***

In [53]:
tf.random.set_seed=42

a =tf.constant(tf.random.uniform(shape=[50],seed=42),shape=[1,1,1,1,50])

In [54]:
# to remove dimentions of 1

tf.squeeze(a)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.95227146, 0.67740774, 0.79531825, 0.75578177, 0.4759556 ,
       0.6310148 , 0.18602037, 0.11430776, 0.3362218 , 0.723335  ,
       0.21919966, 0.8573376 , 0.82392037, 0.59541273, 0.00296271,
       0.24725473, 0.5060741 , 0.36158872, 0.04483843, 0.97216606,
       0.82838845, 0.41458404, 0.601666  , 0.33958685, 0.5731027 ,
       0.23625553, 0.67478454, 0.00732017, 0.02091265, 0.9618796 ,
       0.6345031 , 0.22629452, 0.651536  , 0.8670281 , 0.25453997,
       0.27258146, 0.4647777 , 0.29214978, 0.21008277, 0.42609882,
       0.93323886, 0.4174106 , 0.7148676 , 0.5662477 , 0.30075896,
       0.8497542 , 0.45311093, 0.00433195, 0.09081542, 0.28513503],
      dtype=float32)>

## Lecture 32
**One-hot-encoding**


In [55]:
#one hot  encoding

a = tf.constant([0,1,2,3,4])

tf.one_hot(a,depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [56]:
tf.one_hot(a,depth=4 , on_value="yes" , off_value="no")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes'],
       [b'no', b'no', b'no', b'no']], dtype=object)>

## Lecture 33

math opereation  - square , log ,square root

In [57]:
a = tf.constant([5,10,25,16], dtype=tf.float32)

tf.math.square(a) , tf.math.log(a) , tf.math.sqrt(a)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 25., 100., 625., 256.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.609438 , 2.3025851, 3.218876 , 2.7725887], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2360678, 3.1622777, 5.       , 4.       ], dtype=float32)>)

## Lecture 34

**Nump to tensor and vice-versa**

In [58]:
# when you make a tensor with numpy the datatype will be of 64-bit
a = tf.constant(np.array([1.,2.,3.]))
b = tf.constant([1.,2.,3.])

a.dtype ,b.dtype

(tf.float64, tf.float32)

In [59]:
# we  can convert tensor to numpy and vice-versa

c = a.numpy()
type(c)

numpy.ndarray

## Lecture 35

**Finding Access to GPU**

In [60]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [62]:
!nvidia-smi

Fri Aug 25 18:53:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    31W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------